# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: csdev0
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
